apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - configmap.yaml
  - deployment.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app: mkrew-frontend
  project: mkrew
  tier: frontend

# Opcjonalnie: różne overlay dla env
# bases:
#   - ../base
